gclouddatastore:
  image: risaacson/gcd-local:v1beta2-rev1-3.0.0
  environment:
    - PROJ_ID=customers
  ports:
    - '8080'
api:
  build: .
  ports:
    - '8080'
  links:
    - gclouddatastore
  environment:
    - AUTH0_DOMAIN=bigwednesday-io.eu.auth0.com
    - AUTHO_CLIENT_ID=Jw1aCZI3xZrXzouw7HMkB5wEczIzzdSO
    - AUTH0_CLIENT_SECRET=w9PNqy0DIJ6-hguQTMtxIcXXofhofYYqbLWWEkqVVRX0_-V9ByTvafY-q8uX-TuC
    - AUTH0_CONNECTION=orderable-test-username-password
    - DATASTORE_HOST=http://customersapi_gclouddatastore_1:8080
    - DATASTORE_DATASET=customers
    - GCLOUD_PROJECT_ID=customers
    - GCLOUD_KEY=ewogICJwcml2YXRlX2tleV9pZCI6ICIxMjM0NSIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuMTIzNDU2Nzg5XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAiMTIzLmRldmVsb3Blci5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjEyMy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsCiAgInR5cGUiOiAic2VydmljZV9hY2NvdW50Igp9Cg==
dev:
  build: .
  ports:
    - '8080'
  volumes:
    - .:/src
  working_dir: /src
  links:
    - gclouddatastore
  environment:
    - AUTH0_DOMAIN=bigwednesday-io.eu.auth0.com
    - AUTHO_CLIENT_ID=Jw1aCZI3xZrXzouw7HMkB5wEczIzzdSO
    - AUTH0_CLIENT_SECRET=w9PNqy0DIJ6-hguQTMtxIcXXofhofYYqbLWWEkqVVRX0_-V9ByTvafY-q8uX-TuC
    - AUTH0_CONNECTION=orderable-test-username-password
    - DATASTORE_HOST=http://customersapi_gclouddatastore_1:8080
    - DATASTORE_DATASET=customers
    - GCLOUD_PROJECT_ID=customers
    - GCLOUD_KEY=ewogICJwcml2YXRlX2tleV9pZCI6ICIxMjM0NSIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuMTIzNDU2Nzg5XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAiMTIzLmRldmVsb3Blci5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjEyMy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsCiAgInR5cGUiOiAic2VydmljZV9hY2NvdW50Igp9Cg==
  command: npm run watch
